"""init_models

Revision ID: 19aff94376e2
Revises:
Create Date: 2025-05-09 17:43:27.763590

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19aff94376e2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column(
            "user_uuid",
            sa.UUID(),
            nullable=False,
            comment="Идентификатор пользователя из user_service",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_carts_user_uuid"), "carts", ["user_uuid"], unique=False)
    op.create_index(op.f("ix_carts_uuid"), "carts", ["uuid"], unique=False)
    op.create_table(
        "items",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Название товара",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание товара"),
        sa.Column(
            "price",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Текущая цена товара",
        ),
        sa.Column("category", sa.String(), nullable=False, comment="Категория товара"),
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
            comment="Доступен ли товар для заказа",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_items_uuid"), "items", ["uuid"], unique=False)
    op.create_table(
        "cart_items",
        sa.Column("cart_id", sa.UUID(), nullable=False, comment="Ссылка на корзину"),
        sa.Column("item_id", sa.UUID(), nullable=False, comment="Ссылка на товар"),
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
            comment="Количество товара",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("cart_id", "item_id", name="idx_unique_cart_item"),
    )
    op.create_index(
        op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_cart_items_item_id"), "cart_items", ["item_id"], unique=False
    )
    op.create_index(op.f("ix_cart_items_uuid"), "cart_items", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cart_items_uuid"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_item_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_items_uuid"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_carts_uuid"), table_name="carts")
    op.drop_index(op.f("ix_carts_user_uuid"), table_name="carts")
    op.drop_table("carts")
    # ### end Alembic commands ###
